# In order to generate the schemaSpy documentation of the BETYdb database schema
# (rake task "bety:dbdocs"), you will have to create a configuration file
# "schemaSpyConfig.rb" in this directory and set the required variables giving
# the paths to the needed jar files and the path to the output directory.


# Typical configuration for ordinary usage:

# Download schemaSpy.jar from
# https://www.dropbox.com/s/j50hk7cbqw7680u/schemaSpy.jar?dl=0 and place the
# downloaded file in some accessible location.  (The @schemaSpy variable should
# be set to that location.)  This is a customized version of schema spy made
# especially for the BETYdb Rails app.  Java 1.8 is required to build the
# documentation using this version of the Schema Spy Jar file.
#
@schemaSpy = "~/Applications/SchemaSpy/schemaSpy.jar"

# If you don't have a copy of the Postgres JDBC driver, it may be downloaded
# from https://jdbc.postgresql.org/download.html.  Vertion 9.3-1103 JDBC 41 is
# compatible both with PostgreSQL 9.3 and with Java 1.8.
#
@driver = "~/Applications/SchemaSpy/postgresql-9.3-1103.jdbc41.jar"

# To have the files generated by the customized version of Schema Spy put output
# files in the correct locations in the Rails directory tree, the output
# directory should be set to the Rails root directory.  This is accomplished by
# the following setting:
#
@outdir = "."

# Schema Spy produces some files in the root directory not used by the Rails
# app.  If you are running the version of Schema Spy for BETYdb, you probably
# want to remove them:
#
@remove_root_dir_files = true

# If you typically generate documentation for the production environment, you
# may wish to set @rails_env.  Otherwise, the database for the default
# environment--usually development--will be used.  To avoid having to prefix
# your "rake bety:dbdocs" command with "RAILS_ENV=production" each time you run
# it, use the following setting:
#
# @rails_env = "production"



# Configuration for using the original (non-customized) version of Schema Spy.
# This may be useful for developers.

# Download the Schema Spy Jar file from
# http://sourceforge.net/projects/schemaspy/files/schemaspy/
#
#    @schemaSpy = "~/Applications/SchemaSpy/schemaSpy_5.0.0.jar"
 
# The same driver as above may be used.  Since this version of Schema Spy is
# compatible with Java 5 and later, you could use jdbc3 or jdbc4 if you are
# using Java 5 or Java 6:
#
@driver = "~/Applications/SchemaSpy/postgresql-9.3-1103.jdbc3.jar"

# Use something other that the Rails root directory if you are not using the
# customized version of Schema Spy.  Otherwise the generated files will pollute
# your Rails root directory:
#
# @outdir = "db_docs"
