services:
  # BETY rails frontend to the database
  bety:
    image: pecan/bety:${BRANCH:-latest}
    networks:
      - bety
    ports:
      - 8000
    environment:
      - UNICORN_WORKER_PROCESSES=1
      - SECRET_KEY_BASE=thisisnotasecret
      - GOOGLE_ANALYTICS_ID=G-0000000000
    depends_on:
      - postgres
    restart: unless-stopped

  # postgresql + postgis to hold all the data
  postgres:
    image: postgis/postgis:12-3.3
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - bety
    #ports:
    #  - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  bety:

volumes:
  postgres:
