#!/bin/sh
schemaSpy= #path to schemaSpy executable
outdir= #root directory of bety
user="bety" # username of database
pw="bety" # password of database 
driver= #path to psql driver 

java -jar $schemaSpy  -t pgsql -host localhost -dp $driver -db bety -s public -u $user -p $pw -o $outdir &>/dev/null 

# remove unecessary files generated by schemaSpy 
rm $outdir/deletionOrder.txt $outdir/insertionOrder.txt
rm $outdir/bety.public.xml
rm $outdir/schemaSpy.css