
# rails application database config
production:
  adapter: postgis
  encoding: utf8
  reconnect: false
  database: <%= ENV['BETYDATABASE'] %>
  pool: 5
  username: <%= ENV['BETYUSER'] %>
  password: <%= ENV['BETYPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
